---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-influxdb
  labels:
    app: reporter
spec:
  ports:
    - port: {{ .Values.service.jmeterinfluxdb.apiPort }}
      name: api
      targetPort: {{ .Values.service.jmeterinfluxdb.apiPort }}
    - port: {{ .Values.service.jmeterinfluxdb.httpPort }}
      name: http
      targetPort: {{ .Values.service.jmeterinfluxdb.httpPort }}
    - port: {{ .Values.service.jmeterinfluxdb.graphitePort }}
      name: graphite
      targetPort: {{ .Values.service.jmeterinfluxdb.graphitePort }}
  selector:
    app: reporter
    
---
apiVersion: v1
kind: Service
metadata:
  name: reporter
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: reporter
---
apiVersion: v1
kind: Service
metadata:
  name: jmeter-influxdb-lb
  labels:
    app: reporter
spec:
  type: LoadBalancer
  ports:
    - port: {{ .Values.service.jmeterinfluxdb.apiPort }}
      name: api
      targetPort: {{ .Values.service.jmeterinfluxdb.apiPort }}
      protocol: TCP
  selector:
    app: reporter
  loadBalancerSourceRanges:
  {{ range .Values.service.jmeterinfluxdb.externalRanges }}
    - {{.}}{{ end }}
  